version: '3.4'


services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:management

  portainer:
    image: portainer/portainer

  nse.identidade.api:
    image: ${DOCKER_REGISTRY-}nseidentidadeapi
    build:
      context: .
      dockerfile: src/services/NSE.Identidade.API/Dockerfile     

  nse.catalogo.api:
    image: ${DOCKER_REGISTRY-}nsecatalogoapi
    build:
      context: .
      dockerfile: src/services/NSE.Catalogo.API/Dockerfile     

  nse.clientes.api:
    image: ${DOCKER_REGISTRY-}nseclientesapi
    build:
      context: .
      dockerfile: src/services/NSE.Clientes.API/Dockerfile    

  nse.carrinho.api:
    image: ${DOCKER_REGISTRY-}nsecarrinhoapi
    build:
      context: .
      dockerfile: src/services/NSE.Carrinho.API/Dockerfile    

  nse.pedido.api:
    image: ${DOCKER_REGISTRY-}nsepedidoapi
    build:
      context: .
      dockerfile: src/services/NSE.Pedido.API/Dockerfile    

  nse.pagamento.api:
    image: ${DOCKER_REGISTRY-}nsepagamentoapi
    build:
      context: .
      dockerfile: src/services/NSE.Pagamento.API/Dockerfile    

  nse.bff.compras:
    image: ${DOCKER_REGISTRY-}nsebffcompras
    build:
      context: .
      dockerfile: src/api gateways/NSE.Bff.Compras/Dockerfile   

  nse.webapp.mvc:
    image: ${DOCKER_REGISTRY-}nsewebappmvc
    build:
      context: .
      dockerfile: src/web/NSE.WebApp.MVC/Dockerfile     

  nerdstore-server:
    image: nginx:latest
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile 