version: '3.4'

services:

    sql.data:
        #image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: dev_sql
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - SA_PASSWORD=yourStrong(!)Password
              - ACCEPT_EULA=Y
        healthcheck:
              test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PyourStrong(!)Password", "-Q", "select 1"]
              interval: 1s
              retries: 20
        ports:
              - "1435:1433"
        networks:
              - local

    rabbitmq:
        image: rabbitmq:management
        hostname: rabbit-host
        container_name: rabbit-nerdstore
        ports:
              - 5672:5672
              - 15672:15672
        networks:
              - local
        healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:15672"]
              interval: 30s
              timeout: 10s
              retries: 5


    portainer:
        image: portainer/portainer
        hostname: portainer-host
        container_name: portainer-local
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
          - 9000:9000
          - 8000:8000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    
    nse.identidade.api:
        restart: on-failure
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - ASPNETCORE_URLS=https://+:5001;http://+:4001
              - DOTNET_USE_POLLING_FILE_WATCHER=1
              - CONTAINER=true
        depends_on:
              - sql.data
              - rabbitmq
        ports:
              - "4001:4001"
              - "5001:5001"
        volumes:
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
              - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
              - C:\Users\phill\.nuget\packages\:/root/.nuget/packages:ro
              - ./vsdbg:/vsdbg:ro
              - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
              - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        
        networks:
              - local


    nse.catalogo.api:
        restart: on-failure
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - ASPNETCORE_URLS=https://+:5002;http://+:4002
              - DOTNET_USE_POLLING_FILE_WATCHER=1
              - CONTAINER=true
        depends_on:
              - nse.identidade.api
        ports:
              - "4002:4002"
              - "5002:5002"
        volumes:
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
              - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
              - C:\Users\phill\.nuget\packages\:/root/.nuget/packages:ro
              - ./vsdbg:/vsdbg:ro
              - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
              - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        networks:
              - local

    nse.clientes.api:
        restart: on-failure
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - ASPNETCORE_URLS=https://+:5003;http://+:4003
              - DOTNET_USE_POLLING_FILE_WATCHER=1
              - CONTAINER=true
        depends_on:
              - nse.identidade.api
        ports:
              - "4003:4003"
              - "5003:5003"
        volumes:
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
              - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
              - C:\Users\phill\.nuget\packages\:/root/.nuget/packages:ro
              - ./vsdbg:/vsdbg:ro
              - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
              - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        networks:
              - local

    nse.carrinho.api:
        restart: on-failure
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - ASPNETCORE_URLS=https://+:5004;http://+:4004
              - DOTNET_USE_POLLING_FILE_WATCHER=1
              - CONTAINER=true
        depends_on:
              - nse.identidade.api
        ports:
              - "4004:4004"
              - "5004:5004"
        volumes:
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
              - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
              - C:\Users\phill\.nuget\packages\:/root/.nuget/packages:ro
              - ./vsdbg:/vsdbg:ro
              - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
              - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
        networks:
              - local

    nse.webapp.mvc:
        restart: on-failure
        environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - ASPNETCORE_URLS=https://+:5000;http://+:4000
              - DOTNET_USE_POLLING_FILE_WATCHER=1
              - CONTAINER=true
        depends_on:
              - nse.identidade.api
        ports:
              - "4000:4000"
              - "5000:5000"
        volumes:
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
              - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
              - C:\Users\phill\.nuget\packages\:/root/.nuget/packages:ro
              - ./vsdbg:/vsdbg:ro
              - ${HOME}/.nuget/packages:/root/.nuget/packages:ro
              - ${DOTNET_PATH}/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro  
        networks:
              - local

networks:
    local:
        driver: bridge

volumes:
    portainer_data: