version: '3.4'


services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:management

  portainer:
    image: portainer/portainer

  nse.identidade.api:
    image: ${DOCKER_REGISTRY-}nseidentidadeapi
    build:
      context: .
      dockerfile: src/services/NSE.Identidade.API/Dockerfile     

  nse.catalogo.api:
    image: ${DOCKER_REGISTRY-}nsecatalogoapi
    build:
      context: .
      dockerfile: src/services/NSE.Catalogo.API/Dockerfile     

  nse.clientes.api:
    image: ${DOCKER_REGISTRY-}nseclientesapi
    build:
      context: .
      dockerfile: src/services/NSE.Clientes.API/Dockerfile    

  nse.carrinho.api:
    image: ${DOCKER_REGISTRY-}nsecarrinhoapi
    build:
      context: .
      dockerfile: src/services/NSE.Carrinho.API/Dockerfile    

  nse.webapp.mvc:
    image: ${DOCKER_REGISTRY-}nsewebappmvc
    build:
      context: .
      dockerfile: src/web/NSE.WebApp.MVC/Dockerfile     

  nse.cliente.bff:
    image: ${DOCKER_REGISTRY-}nseclientebff
    build:
      context: .
      dockerfile: src/gateways/NSE.Cliente.BFF/Dockerfile     